CREATE OR REPLACE PACKAGE XXBCM_DATA_MIGRATION_PKG AS
    PROCEDURE XXBCM_ADD_SUPPLIER_ADDRESS;
    PROCEDURE XXBCM_ADD_SUPPLIER;
    PROCEDURE XXBCM_ADD_SUPPLIER_CONTACT;
    PROCEDURE XXBCM_ADD_ORDER_LINES;
    PROCEDURE XXBCM_ADD_INVOICE_HOLDS;
    PROCEDURE XXBCM_ADD_INVOICE_HEADERS;
    PROCEDURE XXBCM_ADD_INVOICE_LINES;
    PROCEDURE XXBCM_ADD_ORDER_HEADERS;
END XXBCM_DATA_MIGRATION_PKG;
/
