-- Execute the Procedure XXBCM_ADD_SUPPLIER_ADDRESS
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_ADDRESS;
END;
/

-- Execute the Procedure XXBCM_ADD_SUPPLIER
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER;
END;
/

-- Execute the Procedure XXBCM_ADD_SUPPLIER_CONTACT
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_SUPPLIER_CONTACT;
END;
/

    -- Execute the Procedure XXBCM_ADD_ORDER_HEADERS
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_HEADERS;
END;

-- Execute the Procedure XXBCM_ADD_ORDER_LINES
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_ORDER_LINES;
END;
/

-- Execute the Procedure XXBCM_ADD_INVOICE_HOLDS
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HOLDS;
END;
/

-- Execute the Procedure XXBCM_ADD_INVOICE_HEADERS
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_HEADERS;
END;
/

-- Execute the Procedure XXBCM_ADD_INVOICE_LINES
BEGIN
    XXBCM_DATA_MIGRATION_PKG.XXBCM_ADD_INVOICE_LINES;
END;
/


/
