-- Supplier Address Table
CREATE TABLE XXBCM_SUPPLIER_ADDRESS (
    ADDRESS_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    ADDRESS_LINE1 VARCHAR2(200) NOT NULL,
    ADDRESS_LINE2 VARCHAR2(200),
    ADDRESS_LINE3 VARCHAR2(200),
    ADDRESS_LINE4 VARCHAR2(200),
    ADDRESS_LINE5 VARCHAR2(200)
);

-- Suppliers Table
CREATE TABLE XXBCM_SUPPLIERS (
    SUPPLIER_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    SUPPLIER_NAME VARCHAR2(200) NOT NULL,
    SUPPLIER_CONTACT_NAME VARCHAR2(200),
    SUPPLIER_ADDRESS_ID NUMBER,
    SUPPLIER_EMAIL VARCHAR2(200),
    CONSTRAINT FK_XXBCM_SUPPLIER_ADDRESS FOREIGN KEY (SUPPLIER_ADDRESS_ID) REFERENCES XXBCM_SUPPLIER_ADDRESS (ADDRESS_ID)
);

-- Supplier Contacts Table
CREATE TABLE XXBCM_SUPPLIER_CONTACTS (
    CONTACT_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    SUPPLIER_ID NUMBER,
    CONTACT_NUMBER VARCHAR2(200) NOT NULL,
    CONSTRAINT FK_XXBCM_SUPPLIER_CONTACT FOREIGN KEY (SUPPLIER_ID) REFERENCES XXBCM_SUPPLIERS (SUPPLIER_ID)
);

-- Order Headers Table
CREATE TABLE XXBCM_ORDER_HEADERS (
    ORDER_HEADER_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    ORDER_REF_NUMBER VARCHAR2(100) NOT NULL,
    ORDER_DATE DATE NOT NULL,
    ORDER_DESC VARCHAR2(500),
    ORDER_TOTAL_AMOUNT NUMBER NOT NULL,
    ORDER_STATUS VARCHAR2(100),
    SUPPLIER_ID NUMBER,
    CONSTRAINT FK_XXBCM_ORDER_SUPPLIER FOREIGN KEY (SUPPLIER_ID) REFERENCES XXBCM_SUPPLIERS (SUPPLIER_ID)
);

-- Order Lines Table
CREATE TABLE XXBCM_ORDER_LINES (
    ORDER_LINE_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    ORDER_HEADER_ID NUMBER,
    ORDER_REF VARCHAR2(100),
    ORDER_LINE_NUM VARCHAR2(100),
    ORDER_LINE_DESC VARCHAR2(500),
    ORDER_LINE_AMOUNT NUMBER NOT NULL,
    ORDER_LINE_STATUS VARCHAR2(100),
    CONSTRAINT FK_XXBCM_ORDER_LINE_HEADER FOREIGN KEY (ORDER_HEADER_ID) REFERENCES XXBCM_ORDER_HEADERS (ORDER_HEADER_ID)
);

-- Invoice Headers Table
CREATE TABLE XXBCM_INVOICE_HEADERS (
    INVOICE_HEADER_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    INVOICE_NUMBER VARCHAR2(100) NOT NULL
);

-- Invoice Holds Table
CREATE TABLE XXBCM_INVOICE_HOLDS (
    INVOICE_HOLD_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    INVOICE_HOLD_REASON VARCHAR2(200) NOT NULL
);

-- Invoice Lines Table
CREATE TABLE XXBCM_INVOICE_LINES (
    INVOICE_LINE_ID NUMBER GENERATED ALWAYS AS IDENTITY START WITH 1 INCREMENT BY 1 PRIMARY KEY,
    INVOICE_HEADER_ID NUMBER,
    INVOICE_NUMBER VARCHAR2(100),
    INVOICE_REFERENCE VARCHAR2(100),
    ORDER_LINE_ID NUMBER,
    INVOICE_DATE DATE NOT NULL,
    INVOICE_DESC VARCHAR2(500),
    INVOICE_AMOUNT NUMBER NOT NULL,
    INVOICE_STATUS VARCHAR2(100),
    INVOICE_HOLD_ID NUMBER,
    CONSTRAINT FK_XXBCM_INVOICE_HEADER FOREIGN KEY (INVOICE_HEADER_ID) REFERENCES XXBCM_INVOICE_HEADERS (INVOICE_HEADER_ID),
    CONSTRAINT FK_XXBCM_INVOICE_LINE_ORDER FOREIGN KEY (ORDER_LINE_ID) REFERENCES XXBCM_ORDER_LINES (ORDER_LINE_ID),
    CONSTRAINT FK_XXBCM_INVOICE_HOLD FOREIGN KEY (INVOICE_HOLD_ID) REFERENCES XXBCM_INVOICE_HOLDS (INVOICE_HOLD_ID)
);

-- Indexes for performance optimization
CREATE INDEX IDX_XXBCM_SUPPLIER_EMAIL ON XXBCM_SUPPLIERS(SUPPLIER_EMAIL);
CREATE INDEX IDX_XXBCM_ORDER_DATE ON XXBCM_ORDER_HEADERS(ORDER_DATE);
CREATE INDEX IDX_XXBCM_ORDER_LINE_AMOUNT ON XXBCM_ORDER_LINES(ORDER_LINE_AMOUNT);
CREATE INDEX IDX_XXBCM_INVOICE_AMOUNT ON XXBCM_INVOICE_LINES(INVOICE_AMOUNT);
